# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Python app to Azure Web App - azurebot-test-1

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Python version
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'
        addToPath: true,
        architecture: 'x64'
    - name: Install Python dependencies
      run: |
        python -m venv env
        cd env/Scripts/
        chmod -R 777 ./activate
        ./activate
        cd ../../
        pip install --install-option="--prefix=$PREFIX_PATH/lib/python3.6" -e ./libraries/botbuilder-schema
        pip install --install-option="--prefix=$PREFIX_PATH/lib/python3.6" -e ./libraries/botframework-connector
        pip install --install-option="--prefix=$PREFIX_PATH/lib/python3.6" -e ./libraries/botbuilder-core
        pip install --install-option="--prefix=$PREFIX_PATH/lib/python3.6" -e ./libraries/botbuilder-integration-aiohttp
        pip install --install-option="--prefix=$PREFIX_PATH/lib/python3.6" -e ./libraries/botbuilder-ai
        pip install --install-option="--prefix=$PREFIX_PATH/lib/python3.6" -e ./libraries/botbuilder-applicationinsights
        pip install --install-option="--prefix=$PREFIX_PATH/lib/python3.6" -e ./libraries/botbuilder-integration-applicationinsights-aiohttp
        pip install --install-option="--prefix=$PREFIX_PATH/lib/python3.6" -e ./libraries/botbuilder-dialogs
        pip install --install-option="--prefix=$PREFIX_PATH/lib/python3.6" -e ./libraries/botbuilder-azure
        pip install --install-option="--prefix=$PREFIX_PATH/lib/python3.6" -e ./libraries/botbuilder-adapters-slack
        pip install --install-option="--prefix=$PREFIX_PATH/lib/python3.6" -e ./libraries/botbuilder-testing
        pip install --target=/opt/hostedtoolcache/Python/3.6.10/x64/lib/python3.6 --user -r requirements.txt
#        cd ../../../../../../opt/hostedtoolcache/Python/3.6.10/x64/lib/python3.6/
#        ls
#        echo "----------------------"
#        ls pkgconfig

    - name: Zip the application files
      run: |
        sudo apt-get install zip gzip tar
        zip -r myapp.zip .
    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v1
      with:
        app-name: 'azurebot-test-1'
        slot-name: 'production'

        publish-profile: ${{ secrets.AzureAppService_PublishProfile_8630fb021e6f4db6a8107f4c9aaca965 }}
        package: './myapp.zip'
